### ISSUE TITLE
Issue with path to Samba

### ISSUE THREAD

**Issue by AdamVenn** [jniltinho/go-samba4_archive#6]
Hi there, love the look of this and would love to try it but... It seems like the interface is looking for Samba in /opt/samba4. I installed Samba on Debian using apt and it ended up at /sbin/samba.
Is there any way to specify the path to Samba?
Thanks for publishing this repo!

**Comment by jniltinho** [comment]
I'm changing the project to Golang, I had to switch to Python for the first version, the next version you will be able to change this configuration.

**Comment by AdamVenn** [comment]
Fair enough. Thanks for the response. Good luck with the next version! For now, I am quickly putting together a small GUI app that will communicate with the DC via SSH. I'll upload it when it's working! Don't think it'll look as nice as your one though!

**Comment by jniltinho** [comment]
@AdamVenn 
I found some software that will help you.

https://directory.apache.org/studio/
http://jxplorer.org/
http://jxplorer.org/downloads/users.html
http://www.ldapadmin.org/
https://www.ldapsoft.com/download.html
https://ldap.com/ldap-tools/

**Comment by jniltinho** [comment]
@AdamVenn 

Gui for Linux
https://github.com/ibv/LDAP-Admin

**Comment by AdamVenn** [comment]
Wow! Thanks @jniltinho ! That's really nice, I'll check them out!
